# Site Build Settings

paginate:            5

# Build settings
markdown:            kramdown
highlighter:         rouge
permalink:           none
plugins:             [jekyll-paginate, jekyll-sitemap, jekyll-feed, jekyll-seo-tag, jekyll-maps]

sass:
  sass_dir: assets/css
  style: :nested

# Customise atom feed settings (this is where Jekyll-Feed gets configuration information)
title:		           "La Dérive Librairie Indépendante"
description:	       "La Dérive Librairie Indépendante et Papeterie à Huy "
author:                "La Dérive sprl"

# RSS 2.0 can be used instead of Atom by uncommenting following two lines
#feed:
#   path:	     rss-feed.xml

maps:
  google:
      api_key: <ADD your API KEY> 
