title:  "La Dérive Librairie"
tagline: "La Dérive Librairie Indépendante Huy"

# Authors documented under _data

# Change to true for Disqus comments
#disqus:
#  comments: false
#  disqus_shortname: 'millennial-3'

menu:
- {name: 'Contact', folder: 'pages', file: 'contact.html'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
- {icon: 'facebook', link: 'https://www.facebook.com/Librairieladerive/'}
- {icon: 'envelope', link: 'mailto:info@laderive.com'}
